#!/usr/bin/env python3
"""scaffold.py - turn a tiny spec into a runnable solve.py that already writes every output file.

    python /harbor/skills/stbench-skill/scaffold.py /app/spec.json [--solve /app/solve.py] [--run]

spec.json (write it in ONE short tool call; strings only):
{
  "output_dir": "/app/output",
  "csv": {"lead_lag_results.csv": ["pair", "lag", "corr"], "summary_table.csv": ["metric", "value"]},
  "json": {"results.json": {"n_obs": "int", "start_date": "str", "best_lag": "int", "same_sign": "bool",
                            "top_pairs": "list", "params": "object"}}
}

What you get:
  - /app/solve.py with load_inputs(), compute(), write_outputs() and main(); compute() returns a
    dict of placeholders shaped exactly like the spec (right file names, columns, keys, types).
  - with --run: solve.py is executed once so every output file exists immediately.
Then replace the placeholders in compute() one function at a time (keep each edit under ~80 lines).
Only the standard library is used here; solve.py itself uses pandas/numpy (present in the task image).
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

PLACEHOLDER = {
    "int": "0", "float": "0.0", "bool": "False", "str": '""', "string": '""',
    "list": "[]", "object": "{}", "dict": "{}", "null": "None", "none": "None",
}

TEMPLATE = '''#!/usr/bin/env python3
"""solve.py - generated by scaffold.py. Fill in compute(); keep write_outputs() as is."""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, "/harbor/skills/stbench-skill")
try:
    import qflib as q  # vetted helpers: returns, vol, VaR, EWMA, lead-lag, BS, first passage, ...
except Exception:  # noqa: BLE001
    q = None

OUTPUT_DIR = {output_dir!r}
CSV_SPEC = {csv_spec!r}      # file -> exact column list (order matters)
JSON_SPEC = {json_spec!r}    # file -> {{key: type}}


def load_inputs():
    """Read every input named in the task. Parse dates explicitly, sort, check shape/dtypes/NaNs."""
    data = {{}}
    # data["prices"] = pd.read_csv("/app/data/prices.csv", parse_dates=["date"]).sort_values("date")
    return data


def compute(data):
    """Return one dict: for each CSV a DataFrame (or list of dicts) with the exact columns;
    for each JSON a dict with the exact keys. Placeholders below - replace step by step."""
    results = {{}}
{csv_blocks}
{json_blocks}
    return results


def _cast(value, typ):
    if value is None:
        return None
    if typ == "int":
        return int(value)
    if typ == "float":
        v = float(value)
        return None if (v != v or v in (float("inf"), float("-inf"))) else v
    if typ == "bool":
        return bool(value)
    if typ in ("str", "string"):
        return str(value)
    if q is not None:
        return q.to_jsonable(value)
    return value


def write_outputs(results):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    for name, cols in CSV_SPEC.items():
        df = results.get(name)
        if not isinstance(df, pd.DataFrame):
            df = pd.DataFrame(df or [], columns=cols)
        df = df.reindex(columns=cols)
        df.to_csv(os.path.join(OUTPUT_DIR, name), index=False)
        print(f"wrote {{name}}: {{len(df)}} rows, columns={{list(df.columns)}}")
    for name, keys in JSON_SPEC.items():
        obj = results.get(name) or {{}}
        out = {{k: _cast(obj.get(k), t) for k, t in keys.items()}}
        with open(os.path.join(OUTPUT_DIR, name), "w", encoding="utf-8") as fh:
            json.dump(out, fh, indent=2)
        print(f"wrote {{name}}: keys={{list(out)}}")


def main():
    data = load_inputs()
    results = compute(data)
    write_outputs(results)


if __name__ == "__main__":
    main()
'''


def _csv_block(name: str, cols: list[str]) -> str:
    return f'    results[{name!r}] = pd.DataFrame(columns={cols!r})  # TODO: rows with exactly these columns\n'


def _json_block(name: str, keys: dict[str, str]) -> str:
    items = ", ".join(f"{k!r}: {PLACEHOLDER.get(str(t).lower(), 'None')}" for k, t in keys.items())
    return f'    results[{name!r}] = {{{items}}}  # TODO: real values, types: {keys!r}\n'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("spec")
    ap.add_argument("--solve", default="/app/solve.py")
    ap.add_argument("--run", action="store_true", help="run the generated solve.py once (creates placeholder outputs)")
    a = ap.parse_args()
    with open(a.spec, encoding="utf-8") as fh:
        spec = json.load(fh)
    output_dir = spec.get("output_dir") or "/app/output"
    csv_spec = {k: list(v) for k, v in (spec.get("csv") or {}).items()}
    json_spec = {k: dict(v) for k, v in (spec.get("json") or {}).items()}
    if not csv_spec and not json_spec:
        print("spec has no csv/json outputs - add at least one", file=sys.stderr)
        return 2
    code = TEMPLATE.format(
        output_dir=output_dir, csv_spec=csv_spec, json_spec=json_spec,
        csv_blocks="".join(_csv_block(n, c) for n, c in csv_spec.items()),
        json_blocks="".join(_json_block(n, k) for n, k in json_spec.items()),
    )
    if os.path.exists(a.solve):
        print(f"{a.solve} exists; not overwriting. Delete it or pass --solve other.py", file=sys.stderr)
        return 3
    os.makedirs(os.path.dirname(os.path.abspath(a.solve)), exist_ok=True)
    with open(a.solve, "w", encoding="utf-8") as fh:
        fh.write(code)
    print(f"wrote {a.solve}: {len(csv_spec)} csv + {len(json_spec)} json outputs -> {output_dir}")
    if a.run:
        r = subprocess.run([sys.executable, a.solve], capture_output=True, text=True)
        print(r.stdout[-2000:])
        if r.returncode != 0:
            print(r.stderr[-2000:], file=sys.stderr)
            return r.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
